# Generated by Django 5.1.4 on 2024-12-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_attachment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
