# Generated by Django 5.1.4 on 2024-12-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0005_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/'),
        ),
    ]
