# Generated by Django 5.1.4 on 2024-12-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0009_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
